Added documentation
Percona-Lab/postgres-tde-ext pull request #17
Opened 2023-09-12 17:41 UTC by dutow

2023-09-13 07:43 UTC, dAdAbird approved these changes
LGTM
just minor grammatical suggestions

2023-09-13 07:43 UTC, dAdAbird commented on README.md
> +This setup is intended for developmenet, and stores the keys unencrypted in the specified data file.
```suggestion
This setup is intended for development and stores the keys unencrypted in the specified data file.
```

2023-09-13 07:43 UTC, dAdAbird commented on README.md
> +Currently the keyring configuration only supports the file provider, with a single datafile parameter.
```suggestion
Currently, the keyring configuration only supports the file provider with a single datafile parameter.
```

2023-09-13 07:43 UTC, dAdAbird commented on README.md
> +3. If postgres is installed in a non standard directory, set the `PG_CONFIG` environment variable to point to the `pg_config` executable
```suggestion
3. If postgres is installed in a non-standard directory, set the `PG_CONFIG` environment variable to point to the `pg_config` executable
```

2023-09-13 09:45 UTC, capri1989 requested changes

2023-09-13 10:00 UTC, dutow commented on README.md
> +6. Create the keyring configuration file (see example keyring configuration)
There's an example later in the file

2023-09-13 17:58 UTC, capri1989 requested changes

2023-09-13 17:58 UTC, capri1989 commented on README.md
> +6. Create the keyring configuration file (see example keyring configuration)
ok but what's needed for the datafile? Just an empty file? What needs to be inside this file in which format?

2023-09-13 18:58 UTC, dutow commented on README.md
> +6. Create the keyring configuration file (see example keyring configuration)
That's created and managed by the server - I'll mention this to the documentation.

2023-09-14 14:51 UTC, dutow commented on README.md
> +1. Install libjson-c-dev: `apt install libjon-c-dev`
I've mentinoed that's an exmaple for ubuntu - as I'm using that, I didn't test other systems.

2023-09-14 14:51 UTC, dutow commented on README.md
> +6. Restart the postgres server
Fixed.

2023-09-14 14:53 UTC, capri1989 approved these changes
LGTM

2023-09-15 09:51 UTC, codeforall approved these changes

2023-09-15 13:56 UTC, merged