Few enhancements and code cleanup around tuple encryption/decryption
Percona-Lab/postgres-tde-ext pull request #52
Opened 2023-10-20 13:15 UTC by codeforall

Along with code cleanup, the PR contains the following noteworthy changes
-- Getting rid of VLAs from the code base
-- Add an interface to move the encrypted data from one location to another.
-- Make the encryption and decryption happen in batches to eliminate the requirement of dynamic allocation in crypt functions.

2023-10-20 18:43 UTC, dAdAbird approved these changes

2023-10-21 06:17 UTC, dutow requested changes
Partial review - I only ran benchmarks because I was curious if the VLA changes cause any measurable change.

Please see my comment, I found a different performance issue in this.

2023-10-21 06:17 UTC, dutow commented on src/encryption/enc_tuple.c
> +	const int enc_log_elevel = DEBUG2;
This is a bad idea: the reason why we don't log anything when ENCRYPTION_DEBUG is off is because of the huge performance hit. Even if the log level is DEBUG2, and it's not enabled, the message will have to go through the logging system logic.

With these changes, the performance hit of encyption drops from <10% to 50%+, and that's with a release build and the debug macros disabled.

We can use the log system if we want to instead of fprintf (not that it makes much difference for these development-only high output debug prints), but please make sure that if ENCRYPTION_DEBUG/KEYRING_DEBUG/... is not defined, we don't call anything related to logging.

2023-10-23 04:26 UTC, codeforall commented on src/encryption/enc_tuple.c
> +	const int enc_log_elevel = DEBUG2;
PR Updated ,with ereport removed when ENCRYPTION_DEBUG is not defined.

2023-10-23 07:02 UTC, dutow commented on src/encryption/enc_tuple.c
> +#ifdef ENCRYPTION_DEBUG
Please keep the old `#if ENCRYPTION_DEBUG` style. `#ifdef` evaulates to true with `#define ENCRYPTION_DEBUG 0`, `#if` evaluates to false.

2023-10-23 07:28 UTC, dutow commented on src/include/encryption/enc_aes.h
> +#define MAX_AES_ENC_KEY_SIZE        ((NUM_AES_BLOCKS_IN_BATCH + 1) * AES_BLOCK_SIZE)
I would use a different name for this - this isn't the size of the key, but the maximum data size when encrypting/decrypting in batches.

2023-10-23 07:28 UTC, dutow commented on src/encryption/enc_aes.c
> +	unsigned char data[MAX_AES_ENC_KEY_SIZE];
Please add at least an assert that dataLen is smaller.

2023-10-23 07:28 UTC, dutow commented on src/encryption/enc_aes.c
> +	unsigned char data[MAX_AES_ENC_KEY_SIZE];
Please add at least an assert that datalen is smaller.

2023-10-23 07:28 UTC, dutow commented on src/encryption/enc_tuple.c
> +    uint64 aes_start_block = start_offset / AES_BLOCK_SIZE;
Why do we have to change this in a code cleanup? We are using C99, where `uint64_t` is the standard type for 64 bit unsigned integers, defined in `stdint.h`. `uint64` is a non standard type.

Also, these variables shouldn't change once calculated, so declaring them `const` is a good practice.

2023-10-23 07:28 UTC, dutow commented on src/encryption/enc_tuple.c
> +	for (block_no = aes_start_block; block_no < aes_end_block; block_no += NUM_AES_BLOCKS_IN_BATCH)
`for (uint64_t block_no = ...)`?

2023-10-23 07:28 UTC, dutow commented on src/encryption/enc_tuple.c
> +	        fprintf(stderr, " >> 0x%02hhX 0x%02hhX\n", v & 0xFF, (v ^ encKey[aes_block_no + i]) & 0xFF);
This is still an `fprintf`, is this intentional?

2023-10-23 12:10 UTC, codeforall commented on src/encryption/enc_tuple.c
> +#ifdef ENCRYPTION_DEBUG
It's entirely a question of style. And IMHO, for enabling/disabling debugging code, it's always easier to spot and use #ifdef regardless of its value.  I am also inclined towards using #ifdef style since it is more consistent with our borrowed code styling. e.g. #ifdef USE_ASSERT_CHECKING and #ifdef USE_PREFETCH

2023-10-23 12:10 UTC, codeforall commented on src/include/encryption/enc_aes.h
> +#define MAX_AES_ENC_KEY_SIZE        ((NUM_AES_BLOCKS_IN_BATCH + 1) * AES_BLOCK_SIZE)
What do you think about MAX_BATCH_AES_ENC_KEY_SIZE? or what is your suggestion?

2023-10-23 12:11 UTC, codeforall commented on src/encryption/enc_aes.c
> +	unsigned char data[MAX_AES_ENC_KEY_SIZE];
will do

2023-10-23 12:11 UTC, codeforall commented on src/encryption/enc_aes.c
> +	unsigned char data[MAX_AES_ENC_KEY_SIZE];
will do

2023-10-23 12:11 UTC, codeforall commented on src/encryption/enc_tuple.c
> +    uint64 aes_start_block = start_offset / AES_BLOCK_SIZE;
uint64 is the standard across PostgreSQL code. So, it's better to stick with PG conventions.

2023-10-26 17:16 UTC, codeforall commented on src/include/encryption/enc_aes.h
> +#define MAX_AES_ENC_KEY_SIZE        ((NUM_AES_BLOCKS_IN_BATCH + 1) * AES_BLOCK_SIZE)
Changed to MAX_AES_ENC_BATCH_KEY_SIZE

2023-10-26 17:18 UTC, codeforall commented
All review comments have been resolved, so merging the PR.

2023-10-26 17:19 UTC, merged