WIP patch for sharing code - Not to be committed
Percona-Lab/postgres-tde-ext pull request #84
Opened 2023-12-07 13:42 UTC by EngineeredVirus

2023-12-07 14:04 UTC, dutow commented on src/access/pg_tde_tdemap.c
> +	key_size = SizeOfRelKeysData(enc_rel_key_data->internal_keys_len);
The function description says that it only writes one key, but here it actually writes all of the internal keys for the table.

2023-12-07 14:07 UTC, dutow commented on src/access/pg_tde_tdemap.c
> +} TDEMapEntry;
The comments say that flags/other data is in this map file, and the other file only contains the keys. However, currently that's not true, the other file also contains the start and end offsets together with the key.

With this design, it would make more sense to store the offsets in the map entry, and keep only the key itself in InternalKey, especially since the offsets can change during an internal key rotation, and we'll want to log those changes.

2023-12-07 14:08 UTC, dutow commented on src/access/pg_tde_tdemap.c
> +	master_key_info = getMasterKey(master_key_name, true, true);
I think we discussed yesterday that we shouldn't create a master key here if one doesn't already exists, as that's an error?

2023-12-07 14:09 UTC, dutow commented on src/access/pg_tde_tdemap.c
> +	/* Add the encrypted key to the data file. */
Incorrect comment? As we are reading here

2023-12-07 17:51 UTC, EngineeredVirus commented on src/access/pg_tde_tdemap.c
> +} TDEMapEntry;
Good point. I think we should remove the following members from the InternalKey structure as these are not being used anywhere in the code and I'm not sure if we'd ever use these.:

`
    Size    start_loc; 
    Size    end_loc;
	void*   ctx; // TODO: shouldn't be here / written to the disk
`

2023-12-07 17:53 UTC, EngineeredVirus commented on src/access/pg_tde_tdemap.c
> +	key_size = SizeOfRelKeysData(enc_rel_key_data->internal_keys_len);
That's a valid point. I'll update the function to ensure that only one key is written.

On a side note, we need to have only one key in the RelKeysData structure. But that requires a longer discussion.

2023-12-07 17:55 UTC, EngineeredVirus commented on src/access/pg_tde_tdemap.c
> +	master_key_info = getMasterKey(master_key_name, true, true);
Good catch. The first argument should be false. And yes, based on yesterday's discussion, I've added a wrapper function.

2023-12-07 17:56 UTC, EngineeredVirus commented on src/access/pg_tde_tdemap.c
> +	/* Add the encrypted key to the data file. */
Copy/paste :)

I've updated the comment.

2023-12-07 17:58 UTC, EngineeredVirus commented on src/access/pg_tde_tdemap.c
> +	InternalKey 	int_key;
Nothing wrong. Just an accidental change sneaked in while I was checking something.

2023-12-07 18:00 UTC, EngineeredVirus commented on src/encryption/enc_aes.c
> +            memset((void *)iv, 0x00, sizeof(TDE_iv));
For the time being, I think this is a fair change. Rather than having multiple copies of the IV in the code, this provides a cleaner view. We can always update as we change it later.

2023-12-07 18:00 UTC, EngineeredVirus commented on src/include/encryption/enc_aes.h
> +extern void AesEncryptKey(const keyInfo *master_key_info, RelKeysData *rel_key_data, RelKeysData *enc_rel_key_data, size_t *enc_key_bytes);
These can always be updated later when we implement the IV change you mentioned above.

2023-12-07 18:01 UTC, EngineeredVirus commented on src/keyring/keyring_api.c
> +const keyInfo* getMasterKey(const char* internalName, int doGenerateKey, int doRaiseError)
I think it's better to keep getting the latest key and generation separate. The wrapper implies the code.

2023-12-07 19:06 UTC, dutow commented on src/keyring/keyring_api.c
> +const keyInfo* getMasterKey(const char* internalName, int doGenerateKey, int doRaiseError)
I agree, I meant that we could change the name of the function to follow the same style as the others.

2023-12-07 19:07 UTC, dutow commented on src/access/pg_tde_tdemap.c
> +} TDEMapEntry;
`start_loc` and `end_loc` will be used for internal key rotation. `ctx` is used, but shouldn't be written to disk, it is a runtime only variable.

2023-12-08 14:00 UTC, dAdAbird requested changes

2023-12-08 14:00 UTC, dAdAbird commented on src/access/pg_tde_tdemap.c
> +	if (FileWrite(keydata_file, enc_rel_key_data, key_size, 0, WAIT_EVENT_DATA_FILE_WRITE) != key_size)
```suggestion
	if (FileWrite(keydata_file, enc_rel_key_data->internal_key, key_size, 0, WAIT_EVENT_DATA_FILE_WRITE) != key_size)
```
?

2023-12-08 14:00 UTC, dAdAbird commented on src/access/pg_tde_tdemap.c
> +	write_pos = TDE_FILE_HEADER_SIZE + (key_index * INTERNAL_KEY_LEN);
Shouldn't be here 
```suggestion
	write_pos = TDE_FILE_HEADER_SIZE + (key_index * SizeOfRelKeysData(1));
```
As we write whole `InternalKey` (with start_loc, end_loc etc) not just a key

2023-12-08 14:00 UTC, dAdAbird commented on src/access/pg_tde_tdemap.c
> +	read_pos = TDE_FILE_HEADER_SIZE + (key_index * INTERNAL_KEY_LEN);
```suggestion
	read_pos = TDE_FILE_HEADER_SIZE + (key_index * SizeOfRelKeysData(key_count));
```

2023-12-08 14:00 UTC, dAdAbird commented on src/access/pg_tde_tdemap.c
> +	enc_rel_key_data = (RelKeysData *) palloc(key_size);
Comment above says `Allocate in TopMemoryContext` so here should be?
```suggestion
	enc_rel_key_data = (RelKeysData *) MemoryContextAlloc(TopMemoryContext, key_size);
```

2023-12-08 14:00 UTC, dAdAbird commented on src/access/pg_tde_tdemap.c
> +
I think we can `pfree(enc_rel_key_data)` now.

2023-12-08 14:00 UTC, dAdAbird commented on src/access/pg_tde_tdemap.c
> +	key_size = SizeOfRelKeysData(enc_rel_key_data->internal_keys_len);
> On a side note, we need to have only one key in the RelKeysData structure. But that requires a longer discussion.

Maybe it worth adding some comment that although `RelKeysData` suppose multiple internal keys, currently we always write and read only one key. I mean the calculation of read/write pos in pg_tde_read/write_keydata() always suppose one key. Add looking for a free spot for only one internalKey in pg_tde_write_map_entry()

2024-01-30 06:42 UTC, closed without merging